# -*- coding: UTF-8 -*-
import os
import sys
import shutil
import subprocess

CURRENT_DIRECTORY = os.path.dirname(os.path.realpath(__file__))
TARGET_FILENAME = 'pe_config'
TARGET_PATH = os.path.join(CURRENT_DIRECTORY, TARGET_FILENAME)

CHECKING_PATHS = os.environ.get('CPLUS_INCLUDE_PATH', '').split(';')

RULE = {
'ENABLE_EIGEN': ['Eigen/Dense'],
'ENABLE_GMP': ['gmp.h'],
'ENABLE_FLINT': ['flint.h'],
'ENABLE_MPFR': ['mpfr.h'],
'ENABLE_MPIR': ['mpir.h'],
'ENABLE_LIBBF': ['libbf.h'],
}

content = []

def add_define(key, value):
  content.append('#ifndef %s'%key);
  content.append('#define %s %s'%(key, value));
  content.append('#endif');
  content.append('');

def check_target(path):
  for folder in CHECKING_PATHS:
    if not os.path.exists(folder):
      continue
    for iter in path:
      if os.path.exists(os.path.join(folder, iter)):
        return True
  return False

def main():
  content.append('#ifndef __PE_CONFIG__');
  content.append('#define __PE_CONFIG__');
  content.append('// This file provides a centralized place to configure pe');
  content.append('');
  content.append('// Auto generated by gen_config.py, and you can edit it manually');
  content.append('');
  content.append('// Configuration priority (first match):');
  content.append('// 1. Compiling command');
  content.append('// 2. The configurations in this file');
  content.append('// 3. The configurations in file pe');
  content.append('');
  add_define('ENABLE_ASSERT', '1');
  add_define('TRY_TO_USE_INT128', '1');
  for (key, value) in RULE.items():
    ok = check_target(value)
    add_define(key, '1' if ok else '0')
  content.append('#endif');
  with open(TARGET_PATH, 'wb') as tempf:
    tempf.write('\r\n'.join(content))

if __name__ == "__main__":
  main()
