name: Tests with gcc

on: [push]

jobs:
  gcc-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ libeigen3-dev libgmp-dev libflint-dev libntl-dev

      - name: Build project
        run: |
          export CPLUS_INCLUDE_PATH="$(pwd)":"/usr/include/flint":"/usr/include/eigen3":${CPLUS_INCLUDE_PATH}
          export LIBRARY_PATH="/usr/lib":${LIBRARY_PATH}
          g++ test/pe_test.c -o ./pe_test.out --std=c++20 -O3 -march=native -mtune=native -fopenmp -lgmpxx -lmpfr -lflint -lntl -lgmp -DENABLE_ASSERT=0 -DTRY_TO_USE_INT128=1 -DENABLE_OPENMP=1 -DENABLE_EIGEN=1 -DENABLE_GMP=1 -DENABLE_FLINT=0 -DENABLE_MPFR=1 -DENABLE_NTL=1 -DENABLE_ZMQ=0 -DENABLE_LIBBF=0 -DENABLE_PRIME_COUNT=0 -DENABLE_PRIME_SIEVE=0 -DTEST_ALL -DCONTINUOUS_INTEGRATION_TEST -DNO_SUPER_TEST

      - name: Run tests
        run: ./pe_test.out

  clang-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang libeigen3-dev libgmp-dev libflint-dev libntl-dev

      - name: Build project
        run: |
          export CPLUS_INCLUDE_PATH="$(pwd)":"/usr/include/flint":"/usr/include/eigen3":${CPLUS_INCLUDE_PATH}
          export LIBRARY_PATH="/usr/lib":${LIBRARY_PATH}
          clang++ test/pe_test.c -o ./pe_test.out --std=c++20 -O3 -march=native -mtune=native -lgmpxx -lmpfr -lflint -lntl -lgmp -DENABLE_ASSERT=0 -DTRY_TO_USE_INT128=1 -DENABLE_OPENMP=0 -DENABLE_EIGEN=1 -DENABLE_GMP=1 -DENABLE_FLINT=0 -DENABLE_MPFR=1 -DENABLE_NTL=1 -DENABLE_ZMQ=0 -DENABLE_LIBBF=0 -DENABLE_PRIME_COUNT=0 -DENABLE_PRIME_SIEVE=0 -DTEST_ALL -DCONTINUOUS_INTEGRATION_TEST -DNO_SUPER_TEST

      - name: Run tests
        run: ./pe_test.out

  msvc-build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1.4.1

      - name: Build project
        run: |
          echo %GITHUB_WORKSPACE%
          cl test\pe_test.c /TP /GS /GL /W3 /Gy /Zc:wchar_t /Zi /Gm- /O2 /Zc:inline /fp:precise /D "NDEBUG" /D "_CONSOLE" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /Gd /Oi /MT /openmp /std:c++20 /FC /EHsc /nologo /diagnostics:classic  /DENABLE_ASSERT=0 /DTRY_TO_USE_INT128=1 /DENABLE_OPENMP=1 /DENABLE_EIGEN=0 /DENABLE_GMP=0 /DENABLE_FLINT=0 /DENABLE_MPFR=0 /DENABLE_NTL=0 /DENABLE_ZMQ=0 /DENABLE_LIBBF=0 /DENABLE_PRIME_COUNT=0 /DENABLE_PRIME_SIEVE=0 /DTEST_ALL /DCONTINUOUS_INTEGRATION_TEST /DNO_SUPER_TEST /I "%GITHUB_WORKSPACE%"

      - name: Run tests
        run: |
          pe_test.exe
