name: C++ Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ libeigen3-dev libgmp-dev libflint-dev libntl-dev

      - name: Build project
        run: g++ test/pe_test.c -o ./pe_test.out --std=c++17 -O3 -march=native -mtune=native -fopenmp -DENABLE_ASSERT=0 -DTRY_TO_USE_INT128=1 -DENABLE_OPENMP=1 -DENABLE_EIGEN=0 -DENABLE_GMP=0 -DENABLE_FLINT=0 -DENABLE_MPFR=0 -DENABLE_NTL=0 -DENABLE_ZMQ=0 -DENABLE_LIBBF=0 -DENABLE_PRIME_COUNT=0 -DENABLE_PRIME_SIEVE=0 -DTEST_ALL -DCONTINUOUS_INTEGRATION_TEST -DNO_SUPER_TEST

      - name: Run tests
        run: ./pe_test.out
